SELECT * from PLAYERS
  JOIN CLUBS on PLAYERS.CLUB_ID = CLUBS.CLUB_ID
  JOIN LEAGUES on CLUBS.LEAGUE_ID = LEAGUES.LEAGUE_ID
    WHERE LEAGUES.LEAGUE_NAME LIKE 'LaLiga';

SELECT FIRST_NAME
  , LAST_NAME
  , to_char(BIRTH_DATE, 'fm dd mon yyyy') BIRTH_DATE
  , POSITION_TITLE
  , CLUB_NAME
  , LEAGUE_NAME
  , COUNTRY_NAME as nationality
  , STATS
  , SKILL_TITLE as skils
FROM PLAYERS
  JOIN CLUBS on PLAYERS.CLUB_ID = CLUBS.CLUB_ID
  JOIN LEAGUES on CLUBS.LEAGUE_ID = LEAGUES.LEAGUE_ID
  JOIN COUNTRIES on PLAYERS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
  JOIN POSITIONS on PLAYERS.POSITION_ID = POSITIONS.POSITION_ID
  JOIN SKILLS on PLAYERS.SKILLS_ID = SKILLS.SKILL_ID
ORDER BY COST DESC;

SELECT
  COUNTRY_NAME,
  LEAGUE_NAME,
  CLUB_NAME,
  COUNT(PLAYER_ID) AS num_of_players
FROM CLUBS
  JOIN LEAGUES ON CLUBS.LEAGUE_ID = LEAGUES.LEAGUE_ID
  JOIN COUNTRIES ON LEAGUES.COUNTRY_ID = COUNTRIES.COUNTRY_ID
  JOIN PLAYERS ON CLUBS.CLUB_ID = PLAYERS.CLUB_ID
GROUP BY COUNTRIES.COUNTRY_NAME, LEAGUE_NAME, CLUB_NAME
ORDER BY COUNTRY_NAME;